[package]
name = "littlefs2"
description = "Rust API for littlefs2"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>", "Brandon Edens <brandonedens@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
categories = ["embedded", "filesystem", "no-std"]
repository = "https://github.com/nickray/littlefs2"

[dependencies]
aligned = "0.3.2"
bitflags = "1.0.4"
cty = "0.2.1"
generic-array = "0.13.2"

# [dev-dependencies]
# trybuild = "1.0"

[dependencies.littlefs2-sys]
# version = "0.1.0"
# path = "../littlefs2-sys"
git = "https://github.com/nickray/littlefs2-sys"
branch = "main"
features = ["assertions", "trace"]
